const faker = require('faker/locale/en');
const fakerList = [];

for (var i = 0; i < 5; i++) {
  fakerList.push({
    list: {
      text: faker.commerce.productName(),
    }
  });
}

module.exports = {
  label: 'Lists',
  context: {
    list: fakerList
  },
  notes: "The div wrapper `entry-content` is auto-generated by WP for content entered in the WP editor. It's used here as a styling hook so that lists used for accessibility in components are not styled by this object."
};
