name: Visual Tests
on: push
jobs:
  test:
    name: Percy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run percy test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run percy
