# Created from starter workflow for GitHub Pages; see: https://github.com/actions/starter-workflows/blob/main/pages/static.yml

name: Publish to GitHub Pages
on: push
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Set Font Awesome token and dry run installation
        run: |
          npm config set '@fortawesome:registry=https://npm.fontawesome.com/'
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_TOKEN }}"
          npm install @fortawesome/fontawesome-pro --dry-run
      - name: Install dependencies
        run: npm ci
      - name: Create build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload build
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
